### ISSUE TITLE
iri-string v0.3.0 fail to be resolved as dependency

### ISSUE THREAD

**Issue by luyao0412** [lo48576/iri-string#3]
Hi, I met the follwoing error when using iri-string v0.3.0 as dependency.
Thanks.
PS C:\Users\usluyao\Desktop\help\Learn\Rust\Hands-On-Microservices-with-Rust-master\playground\json-validation-test> cargo run
Compiling iri-string v0.3.0
error[E0210]: type parameter S must be used as the type parameter for some local type (e.g., MyStruct<S>)
--> C:\Users\usluyao.cargo\registry\src\github.com-1ecc6299db9ec823\iri-string-0.3.0\src\types\generic\macros.rs:15:14
|
15 | impl<S: crate::spec::Spec> From<&$ty> for $($smartptr)::* <$ty> {
| ^ type parameter S must be used as the type parameter for some local type
|
::: C:\Users\usluyao.cargo\registry\src\github.com-1ecc6299db9ec823\iri-string-0.3.0\src\types\generic\absolute.rs:10:1
|
10 | / define_custom_string_slice! {
11 | | /// A borrowed slice of an absolute IRI without fragment part.
12 | | ///
13 | | /// This corresponds to [absolute-IRI rule] in [RFC 3987]
... |
80 | | }
81 | | }
| |_- in this macro invocation
|
= note: only traits defined in the current crate can be implemented for a type parameter

error[E0210]: type parameter S must be used as the type parameter for some local type (e.g., MyStruct<S>)
--> C:\Users\usluyao.cargo\registry\src\github.com-1ecc6299db9ec823\iri-string-0.3.0\src\types\generic\macros.rs:15:14
|
15 | impl<S: crate::spec::Spec> From<&$ty> for $($smartptr)::* <$ty> {
| ^ type parameter S must be used as the type parameter for some local type
|
::: C:\Users\usluyao.cargo\registry\src\github.com-1ecc6299db9ec823\iri-string-0.3.0\src\types\generic\absolute.rs:10:1
|
10 | / define_custom_string_slice! {
11 | | /// A borrowed slice of an absolute IRI without fragment part.
12 | | ///
13 | | /// This corresponds to [absolute-IRI rule] in [RFC 3987]
... |
80 | | }
81 | | }
| |_- in this macro invocation
|
= note: only traits defined in the current crate can be implemented for a type parameter

error[E0210]: type parameter T must be used as the type parameter for some local type (e.g., MyStruct<T>)
--> C:\Users\usluyao.cargo\registry\src\github.com-1ecc6299db9ec823\iri-string-0.3.0\src\types\generic\macros.rs:97:36
|
97 | impl<S: crate::spec::Spec, T: crate::spec::Spec> PartialEq<$ty_lhs> for $ty_rhs {
| ^ type parameter T must be used as the type parameter for some local type
|
::: C:\Users\usluyao.cargo\registry\src\github.com-1ecc6299db9ec823\iri-string-0.3.0\src\types\generic\absolute.rs:84:1
|
84 | / define_custom_string_owned! {
85 | | /// An owned string of an absolute IRI without fragment part.
86 | | ///
87 | | /// This corresponds to [absolute-IRI rule] in [RFC 3987]
... |
108 | | }
109 | | }
| |_- in this macro invocation
|
= note: only traits defined in the current crate can be implemented for a type parameter

error[E0210]: type parameter T must be used as the type parameter for some local type (e.g., MyStruct<T>)
--> C:\Users\usluyao.cargo\registry\src\github.com-1ecc6299db9ec823\iri-string-0.3.0\src\types\generic\macros.rs:109:36
|
109 | impl<S: crate::spec::Spec, T: crate::spec::Spec> PartialOrd<$ty_lhs> for $ty_rhs {
| ^ type parameter T must be used as the type parameter for some local type
|
::: C:\Users\usluyao.cargo\registry\src\github.com-1ecc6299db9ec823\iri-string-0.3.0\src\types\generic\absolute.rs:84:1
|
84 | / define_custom_string_owned! {
85 | | /// An owned string of an absolute IRI without fragment part.
86 | | ///
87 | | /// This corresponds to [absolute-IRI rule] in [RFC 3987]
... |
108 | | }
109 | | }
| |_- in this macro invocation
|
= note: only traits defined in the current crate can be implemented for a type parameter

error[E0210]: type parameter S must be used as the type parameter for some local type (e.g., MyStruct<S>)
--> C:\Users\usluyao.cargo\registry\src\github.com-1ecc6299db9ec823\iri-string-0.3.0\src\types\generic\macros.rs:91:14
|
91 | impl<S: crate::spec::Spec, T: crate::spec::Spec> PartialEq<$ty_rhs> for $ty_lhs {
| ^ type parameter S must be used as the type parameter for some local type
|
::: C:\Users\usluyao.cargo\registry\src\github.com-1ecc6299db9ec823\iri-string-0.3.0\src\types\generic\absolute.rs:84:1
|
84 | / define_custom_string_owned! {
85 | | /// An owned string of an absolute IRI without fragment part.
86 | | ///
87 | | /// This corresponds to [absolute-IRI rule] in [RFC 3987]
... |
108

**Comment by lo48576** [comment]
Thank you for reporting.

Could you tell me what version of rustc do you use?
This crate should compile with Rust 1.41, but is not guaranteed to compile with versions before that.
(cf. <https://github.com/rust-lang/rust/blob/1.42.0/RELEASES.md#language-1>, <https://github.com/rust-lang/rust/pull/65879/>.)

**Comment by luyao0412** [comment]
This is resolved by upgrading rustc version. Thanks for the instruction.
